pacak/cargo-show-asm

src/main.rs

Fixes https://github.com/pacak/cargo-show-asm/issues/1

Slightly improved windows relative path glob hack

---

src/asm.rs

fixes #4
* raise errors for failed parse
* correctly report errors for misparse (i.e. if entire file wasn't parsed)

fix handling of arm assembly

---

Cargo.lock
Cargo.toml
src/opts.rs

Update to bpaf 0.5.0

---

src/asm.rs

First of all, thanks for this amazing util! I've been using it daily. 🙌
I don't know exactly when, but recent versions of nightly broke the `--rust` flag.
The directive's format changed from (e.g.):
```
.file   1 "/rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs"
```
to:
```
.file   1 "/rustc/c07a8b4e09f356c7468b69c50cac7fc5b5000b8a/library/std/src/sys_common" "backtrace.rs"
```
This PR fixes parsing for the latest Rust nightly, while also maintaining backwards-compatibility with previous format.

Fix parsing of file directive on nightly

---

Cargo.lock
Cargo.toml
Changelog.md
src/opts.rs

select the right package in non-virtual workspaces too

---

README.md

I took some liberties with the phrasing of the list you paste everywhere, happy to adjust the phrasing if you don't like my adjustments.

Add a section about cargo-asm, fix spelling

---

Changelog.md
src/asm.rs

When dumping a function - dump whole section

---

Cargo.lock
Cargo.toml
Changelog.md

- update dependenies + bpaf
- optional colorful command line parser output

Release 0.1.23

---

Cargo.lock
Cargo.toml
Changelog.md
README.md
src/asm.rs
src/main.rs
src/opts.rs

Fixes https://github.com/pacak/cargo-show-asm/issues/63
Fixes #65 
Fixes #64

support custom profiles

---

Cargo.lock
Cargo.toml
Changelog.md
README.md
src/asm.rs
src/demangle.rs
src/llvm.rs
src/main.rs
src/mir.rs
src/opts.rs

- replaced libcargo with invoking cargo
Thanks to oxalica
- renamed `--feature` -> `--features`
- dropped backward compatibility `-no-defaut-features`
- implemented `--everything` to dump the whole file demangled
- various optimizations

Release 0.2.0

---

.github/workflows/check-and-lint.yaml
src/asm.rs
src/asm/statements.rs
src/main.rs

Add a fallback for same_file that would compare file contents

---

src/asm.rs
src/main.rs
src/mir.rs

get --color and --no-color working again

---

Cargo.lock
Cargo.toml
Changelog.md
README.md
src/lib.rs
src/main.rs
src/opts.rs

include README into docs.rs page, release 0.2.5

---

Cargo.lock
Cargo.toml
Changelog.md
README.md
src/main.rs
src/opts.rs

- add --wasm flag
- Update Changelog, release 0.2.6
Fixes https://github.com/pacak/cargo-show-asm/issues/91

Release 0.2.6

---

Cargo.lock
Cargo.toml
Changelog.md
sample/src/lib.rs
src/asm.rs
src/main.rs

- support mangled names
- fix select-by-index

Release 0.2.7

---

Cargo.lock
Cargo.toml
Changelog.md

- improve error messages
- properly handle exception handling code on Windows
thanks to @al13n321
- support --rust on Windows
thanks to @al13n321

Release 0.2.9

---

.github/workflows/check-and-lint.yaml
src/asm.rs
src/asm/statements.rs
src/cached_lines.rs
src/lib.rs
src/llvm.rs
src/main.rs
src/mir.rs
src/opts.rs

Fixes #122 
Fixes #114
Fixes #111

Decouple scanning, printing and suggesting things

---

Cargo.lock
Cargo.toml
Changelog.md
README.md
src/asm.rs
src/lib.rs
src/main.rs
src/mca.rs
src/opts.rs

- pass `-Z` flags to cargo
- support `llvm-mca`

release 0.2.12

---

Changelog.md
src/main.rs

Release 0.2.15

---

Cargo.lock
Cargo.toml
Changelog.md
src/asm.rs

- support for strange looking rust sources names
- less dependencies

Release 0.2.16

---

src/asm.rs

fallback to displaying an error if source code can't be found
Fixes #157

factor out search for source code,

---

Changelog.md

- look harder for source code, don't panic if it can't be found
- bump deps

Release 0.2.17

---

Cargo.lock
Cargo.toml
Changelog.md
src/asm.rs
src/llvm.rs
src/mca.rs
src/mir.rs

Release 0.2.21

---

Changelog.md
LICENSE-APACHE
LICENSE-MIT

Include license files

---

Cargo.lock
Cargo.toml
Changelog.md
src/asm.rs

- better support for no_mangle in MacOS (#217)
- ignore empty source files - seen them on Windows (#215)
- bump a bunch of deps
- add license files (#213)

Release 0.2.22

---

Cargo.lock
Cargo.toml
Changelog.md
README.md
src/asm.rs
src/opts.rs

- Add an option to strip blank lines and make it default, original behavior is accessible
with `-B` option
Fixes #220

Release 0.2.23

---

Cargo.lock
Cargo.toml
Changelog.md
src/asm.rs
src/asm/statements.rs
src/demangle.rs
src/llvm.rs
src/mca.rs

- add an option to keep mangled name, thanks to @osiewicz
- add syntax highlight for mangled names
- bump dependencies

Release 0.2.24

---

Cargo.lock
Cargo.toml
Changelog.md

- Display more accurate count of LLVM lines

Release 0.2.25

---

Cargo.lock
Cargo.toml
Changelog.md

- avoid using hard to see colors
thanks to @epontan
- bump deps

Release 0.2.26

---

Cargo.lock
Cargo.toml
Changelog.md
src/lib.rs

- fix function selection by index, see https://github.com/pacak/cargo-show-asm/issues/244
Fixes #244

Release 0.2.29

---

src/asm.rs
src/lib.rs

For all those who are trying to compile cargo-show-asm with older compiler

Replace RPITIT with more conservative approach

---

src/asm.rs

We normally identify functions by spotting name-mangled labels, so to find in particular the non-mangled entry point function we must instead look for a different marker.  Thankfully the reason to use #[no_mangle] is to make a public symbol so the relevant symbols show up with asm like
.section	.text,"xr",one_only,_mainCRTStartup
.globl	_mainCRTStartup
.p2align	4, 0x90
_mainCRTStartup:
Fixes #281.

gather #[no_mangle] functions from windows output

---

Cargo.lock
Cargo.toml
Changelog.md

- even better support for no_mangle names on windows
thanks to @evmar
- bump deps

Release 0.2.36

---

Cargo.lock
Cargo.toml
Changelog.md
src/main.rs

- Smarter artifact detection, shouldn't panic with wasm crates, Fixes #292
- Bump deps

Release 0.2.38

---

src/llvm.rs

In LLVM-IR output mode `cargo asm` don't parse non-mangled function definitions properly and return function names like `Function Attrs: mustprogress nofree noinline norecurse nosync nounwind nonlazybind willreturn memory(none) uwtable` instead.
In ASM output mode everything is okay.
Checked with example about on linux x86_64 and with cargo test.
> [!WARNING] 
> The changes have not been tested on a large number of samples and in theory may break something.
> Since the conditions for detecting functions have been relaxed, it now you can theoretically over-detect functions.
> Please check on more "real" examples if possible.
- `#[no_mangle]` functions don't always start with `_`: requirement for `_` prefix removed,
- `no_mangle` function will not contain a comment with its name beforehand, …

Fix no_mangle function search in LLVM-IR output mode

---

Changelog.md
src/asm.rs
src/asm/statements.rs

Parse data lines and use them to scan for constants instead of looking for sections
Fixes #315

Smarter approach for detecting constants

---

.github/check.sh
.github/workflows/check-and-lint.yaml
Changelog.md
sample_merged/src/lib.rs
src/asm.rs
src/asm/statements.rs

Instead of "see if it runs" new CI tries to compare output from the master branch to the output from the feature branch on several different examples.
Fixes #79

CI refactor

---

src/asm/statements.rs

Use smarter regexp to detect data declarations

---

src/disasm.rs

Proposes a change that introduces Thumb-v2 and Arm instruction set disassembly for ARM ELF files.

ARM disassembly support

---

Cargo.lock
Cargo.toml
src/asm.rs

+ bump serde dependenciy that was pinned because of it shipping binary blob

Better error

---

Cargo.lock
Cargo.toml

- improve error for mismaching/corrupted rust-src
- support for ARM disassembly
thanks @fg-cfh
- bump deps

Release 0.2.44

---

Cargo.lock
Cargo.toml
Changelog.md

- `--silent` flag can be used to suppress some of the user directed informatin thanks @tgross35

Release 0.2.46

---

README.md
src/opts.rs

add short arg `-F` to complement `--features`

---

Cargo.lock
Cargo.toml
src/asm.rs
src/asm/statements.rs

Upgrade `nom` to 8.0

---

src/disasm.rs
src/llvm.rs
src/main.rs
src/opts.rs

This bumps the MSRV to 1.82 (if it wasn't that before). Not sure if that's acceptable.

Fix new-ish clippy lints
