pacak/cargo-show-asm

Cargo.lock, Cargo.toml
This reduces build times slightly, and removes memoffset as an indirect dependency.
=> Upgrade nix to 0.24.1, limit features

src/opts.rs
The command currently takes the option `--defaut-features` (sic) which differs from other Cargo subcommands. This patch corrects the spelling to `--default-features` and adds the old option name as a hidden alias in case user scripts use it.
=> Fixed spelling of `--default-features` command line option

src/main.rs
Example source code:
```
use rand;
fn main() {
let mut num1: i32 = rand::random();
let mut num2: i32 = rand::random();
num1 = num1 % 100;
num2 = num2 % 100;
println!("{}", num1 * num2);
}
```
Can't be printed as asm with `cargo asm learn_codegen::main -v --rust --target=x86_64-apple-darwin` on M1
It falls with :
```
error[E0461]: couldn't find crate `rand` with expected target triple x86_64-apple-darwin
--> src/main.rs:1:5
|
1 | use rand;
|     ^^^^
|
= note: the following crate versions were found:
crate `rand`, target triple aarch64-apple-darwin:
```
Because `asm show` builds dependencies with Host's arch.
=> Fixes compilation if --target is requested and file has dependencies.

Cargo.toml, Changelog.md, src/asm.rs
```
% cargo asm -p mini-std lerp32 --rust
Finished release [optimized + debuginfo] target(s) in 0.24s
You need to install rustc sources to be able to see the rust annotations, try
rustup component add rust-src
% rustup component add rust-src
info: downloading component 'rust-src'
info: installing component 'rust-src'
% cargo asm -p mini-std lerp32 --rust
Finished release [optimized + debuginfo] target(s) in 0.23s
mini_std::math::lerp32:
.Lfunc_begin39:
...
```
=> Detect missing sources and suggest to install them

Cargo.lock, Cargo.toml, Changelog.md, src/opts.rs
I'm using the `workspace-inheritance` feature from cargo 0.65, which makes this tool fail to run:
```
Error: failed to parse manifest at `.../Cargo.toml`
Caused by:
feature `workspace-inheritance` is required
The package requires the Cargo feature called `workspace-inheritance`, but that feature is not stabilized in this version of Cargo (1.63.0).
Consider adding `cargo-features = ["workspace-inheritance"]` to the top of Cargo.toml (above the [package] table) to tell Cargo you are opting in to use this unstable feature.
See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#workspace-inheritance for more information about the status of this feature.
``` 
So this updates cargo and the rest of the dependencies, and bump the version to 0.1.20
=> Update dependencies (support the new workspace-inheritance feature)

README.md
Use "console" for terminal codeblocks and "$" for shell prompt.
=> Fix console session codeblocks

Cargo.lock, Cargo.toml
The openssl installation situation on macOS is terrible 🤝 horrible 🤝 no good 🤝 very bad, so it's common for applications that depend on `cargo` to expose this alternative.
- https://github.com/kbknapp/cargo-outdated/blob/v0.11.1/Cargo.toml#L50
- https://github.com/rust-secure-code/cargo-geiger/blob/cargo-geiger-0.11.4/cargo-geiger/Cargo.toml#L39
- https://github.com/est31/cargo-udeps/blob/v0.1.32/Cargo.toml#L16
- https://github.com/nabijaczleweli/cargo-update/blob/v8.2.0/Cargo.toml#L92
Without vendored openssl, installation fails on macOS with:
<details>
<summary>...</summary>
```console
error: linking with `cc` failed: exit status: 1
|
= note: "cc" "-arch" "arm64" "/var/folders/jm/n9f0cy6n27n2cr0q4l3009dw0000gn/T/rustcgAqSq1/symbols.o" …
```
=> Expose cargo's vendored-openssl feature

Cargo.lock, Cargo.toml, src/asm.rs
Fixes #31
Proper relative label renaming is mildly annoying since it is affected by printing/not printing rust code, empty line deduplication and so on.
=> Delabel followup

Cargo.lock, Cargo.toml, Changelog.md
- strip redundant labels by default
- removing `glob` in `favor of std::fs` - windows CI now works
- document completions
=> Release 0.1.22

Cargo.lock, Cargo.toml, src/main.rs, src/opts.rs
Fixes #69 
This PR is an incomplete draft for more discussion.
- `--lib`, `--test`, `--bench`, `--package` selectors, and auto-selection are implemented. Asm paths are constructed precisely without guessing.
- ~`--bin`, `--example` are not implemented, which need file searching and guessing. We could construct asm paths using unstable `--build-plan` arguments but not sure that's acceptable.~
`--bin`, `--example` are implemented by tracking hard-links to get the asm file name.
- ~`--release`, `--dry-run` and etc flags should be trivial by passing-through. They are not implemented yet to focus on the overall approach.~ Implemented.
Currently we use some kind of guessing for extra-filenames (the hash part in filename), which may need `cargo clean` before the run. It's kind of annoying to …
=> [PoC] Replace libcargo with cargo CLI

Cargo.lock, Cargo.toml, Changelog.md, README.md
- number of MacOS specific bugfixes
- update deps
- more detailed output with verbosity flags
Fixes #76
=> Prepare to release 0.2.1

Cargo.lock, Cargo.toml, Changelog.md, src/asm.rs, src/opts.rs
`--simplify` option to strip some of the redundant info
Fixes https://github.com/pacak/cargo-show-asm/issues/86
=> Prepare to release 0.2.4

src/asm.rs, src/asm/statements.rs, src/demangle.rs
This PR adds a few things
* detection for new local label types like `LBB0_1` and `Ltmp12`
* colorizing labels in arguments
* packing the assembly together (this last one could be optional behind a flag, but I really like the packed look)
See before and after below.
A few things to note:
* the many `Ltmp*` labels went away (which is super nice!)
* the `LBB` labels stayed when they are used
* you can easily see labels in arguments, so tracing control flow is a lot easier 
* assembly is packed (which I prefer)
<details>
<summary> comparison </summary>
Before:
After:
After (if packing is dropped)
</details>
=> Improve labels and add more coloring

src/main.rs
Fixes cargo's diagnostics not being in color even when color is enabled/supported.
=> Fix color messages from cargo

Cargo.toml, Changelog.md
Mostly dependency bump, should improve error messages from bpaf a bit
=> Prepare to release 0.2.8

src/asm/statements.rs
On Windows, the .s file generated by rust compiler has slightly different directives for pointing to source code files and line numbers:
* Instead of `.file fileno [dirname] "filename" [md5]` there's `.cv_file fileno "filename" ["checksum"] [checksumkind]`
* Instead of `.loc fileno lineno [column] [options]` there's `.cv_loc functionid fileno lineno [column] [prologue_end] [is_stmt value]`
Source: https://llvm.org/docs/Extensions.html#codeview-dependent
This PR makes cargo-show-asm recognize these.
(Idk if there's a way to make rustc produce the directives in different format instead.)
Tested manually on a small program on Windows. Didn't test on Unix, but all modified code is covered by unit tests, and `cargo test` passes.
=> Make --rust work on Windows (by supporting .cv_file and .cv_loc directives)

Cargo.lock, Cargo.toml, Changelog.md
- fix filtering by index and name at the same time
- --test, --bench, etc can be used without argument to list available items
thanks to @danielparks
- bump deps
=> Release 0.2.11

.github/workflows/check-and-lint.yaml, sample/src/lib.rs, src/main.rs, src/opts.rs
Fixes: #142.
Additionally, this includes one style-only fix:
- consistently place the bpaf attribute for `unstable` before the doc comment.
=> Add --llvm-input and -C flags

src/main.rs
The primary purpose of setting debuginfo=2 is to map back from ASM/WASM output to rust source. That's not necessary for LLVM IR output, or MCA, and LLVM IR gets substantially cleaner *without* debuginfo.
However, debuginfo=2 is also (currently) needed for function boundary detection on ASM output on both Windows and Mac OS.
Related: https://github.com/pacak/cargo-show-asm/pull/143#discussion_r1114247796
=> only add debuginfo=2 when generating asm/wasm

Cargo.lock, Cargo.toml, Changelog.md, src/asm.rs, src/lib.rs, src/llvm.rs, src/main.rs, src/mca.rs, src/mir.rs
- Allow to pass -C flags directly to rustc
- --llvm-input to show llvm-ir before any LLVM passes
- Only generate debug info for LLVM resulting in cleaner
Thanks to @jonasmalacofilho
- clippy things
- dependencies
=> Release 0.2.14

Cargo.lock, Cargo.toml, Changelog.md, src/opts.rs
- you can also specify default profile using `CARGO_SHOW_ASM_PROFILE` env variable
- bump bpaf to 0.8.0, add dull colors by default
Helps with #163
=> Release 0.2.18

Cargo.lock, Cargo.toml, Changelog.md, README.md, README.tpl, sample/Cargo.toml, src/main.rs, src/opts.rs
- workaround for lto in 1.67.1 is removed - users can pass it manually with `-Clto=no` or something
- workaround for fancier debuginfo in 1.71.0 is added - will remove it once cargo-metadata updates
- documentation is now generated in markdown
Fixes #186 
Addresses an issue in #187
=> Release 0.2.20

.github/workflows/check-and-lint.yaml, sample_cdylib/src/lib.rs, src/asm.rs
Currently, `no_mangle` functions are not being found on macOS because de-mangling fails & the .text sections are a different format on macOS.
This PR adds support for finding `no_mangle` attributes in macOS using the `.globl` directive & refactors `asm::find_items` a little to reduce nesting.
Related: #137
=> Adds support for `no_mangle` in macOS

.github/workflows/check-and-lint.yaml, README.md, src/asm.rs, src/lib.rs, src/llvm.rs, src/mca.rs, src/mir.rs, src/opts.rs
This commit adds two new switched (--keep-mangled and --demangle) where --demangle is specified by default. keep-mangled can be useful when one wants to do the demangling themselves with a different library than rustc_demangle (e.g. to analyze symbol names with [ast-demangle](https://github.com/EFanZh/ast-demangle)).
=> feat: Parameterize symbol demangling on command line.

src/asm.rs, src/asm/statements.rs
This adds a new format specifier support (-) to Instruction's Display implementation.
Output of `cargo run -- --keep-mangled --lib -C symbol-mangling-version=v0  --asm 4` (shortened for brevity):
Without `--keep-mangled`:
```
mov w0, #8
mov w1, #24
bl alloc::alloc::handle_alloc_error
```
With `--keep-mangled`:
```
mov w0, #8
mov w1, #24
bl __ZN5alloc5alloc18handle_alloc_error17h04014ba8bc4ecf83E
```
With `--full-name`:
```
mov w0, #8
mov w1, #24
bl alloc::alloc::handle_alloc_error::h04014ba8bc4ecf83
```
=> feat: Optionally leave function names in asm listings unmangled.

sample/src/lib.rs, sample_rlib/lib.rs
The culprit lied in https://github.com/rust-lang/rust/pull/116505
In short, with default features turned off, main was trivial enough to
be marked as inline function automatically which then made the symbol
weak. Since nobody was referencing it, it got stripped away.
Marking main in default-features=false config as #[inline(never)] or
replacing 1 + 1 in it's body with a simple println!("foo") call (to make
the main function sophisticated enough not to be subject to the new
automatic marking as inline) makes the test pass again.
=> Trying to fix CI failure

src/asm/statements.rs, src/demangle.rs, src/llvm.rs
The use of `OwoColorize::bright_black()` seem to affect a lot of users with dark color schemes as it makes parts of the output unreadable.
Avoid the explicit usage of black color and replace all occurrences with a suitable alternate color.
Fixes #170
=> Avoid usage of bright_black color

Cargo.lock, Cargo.toml, Changelog.md, src/asm.rs
- look for rustc (not stdlib!) source code in the right place
Fixes https://github.com/pacak/cargo-show-asm/issues/238
=> Relese 0.2.27

Cargo.lock, Cargo.toml, Changelog.md, README.md, src/asm.rs, src/lib.rs, src/main.rs, src/opts.rs
- Add a set of options to limit rust source code to workspace, regular crates or all available  code:
--this-workspace      Show rust sources from current workspace only
--all-crates          Show rust sources from current workspace and from rust registry
--all-sources         Show all the rust sources including stdlib and compiler
- Bump deps
Fixes #241
=> Release 0.2.28

Cargo.lock, Cargo.toml, Changelog.md, README.md, README.tpl, sample/src/lib.rs, src/asm.rs, src/demangle.rs, src/lib.rs, src/llvm.rs, src/mca.rs, src/mir.rs, src/opts.rs
- `cargo asm --context 1 foo` will print function `foo` as well as all the local functions `foo` calls. fixes #247 
- bump deps (supports-color is used twice for now)
=> Release 0.2.30

Cargo.toml, Changelog.md, README.md, README.tpl, sample/src/lib.rs, src/asm.rs, src/asm/statements.rs, src/demangle.rs, src/lib.rs, src/llvm.rs, src/main.rs, src/mca.rs, src/mir.rs, src/opts.rs
Thanks for a great tool!  I used it a bit for my attempts at making Rust [a bit faster](https://github.com/rust-lang/rust/pull/121001) (no luck so far, but hopeful), so figured will contribute a bit back.
* introduced a new `Dumpable` trait and made MIR and LLVM implement it - so that `dump_function` can share both implementations (it was identical for both)
* removed a few un-needed/inconsistent qualifiers
* ran spellchecker
* inlined a few format args
=> Some minor linting, spelling, and code de-dup

.github/workflows/release-plz.yml, .github/workflows/release.yml, Cargo.toml, cliff.toml, release-plz.toml
`git-cliff` -> `release-plz` -> `cargo-dist`
`git-cliff`:
- update changelog
`release-plz`:
- Publish on crates.io
- Create and push a git tag
`cargo-dist`:
- Build and create installers
- Create release
> Release-plz makes releasing Rust packages child's play:
> 
> For every commit, release-plz creates a release Pull Request from CI.
> The release Pull Request reminds the maintainer about the unpublished changes.
> The maintainer reviews and merges the pull request.
> Release-plz releases the updated packages from CI.
> In short, release-plz makes releasing Rust packages as easy as clicking the pull request "merge" button.
@pacak You will need to follow this guide in order to finish setting up the PR:
https://release-plz.ieni.dev/docs/github/quickstart
Fixes #240
=> feat(CI): automate release

Cargo.lock, Cargo.toml
- include relevant constants in produced asm output, this can be disabled with `--no-constants` [#261]
- bump deps
- lower MSRV
=> Release 0.2.31

Changelog.md, README.md, src/opts.rs
You can pass `--include-constants` to see them
=> Don't include constants by default - noisy

Cargo.lock, Cargo.toml, Changelog.md, src/disasm.rs
- don't include constants by default, pass `--include-constants` to get them back.
- include local jump labels in disassembly
- include instructions in hex in disassembly, pass `--simplify` to drop them
- avoid memory addresses with displacement in disassembly
- bump bpaf
=> Relese 0.2.35

Cargo.lock, Cargo.toml, Changelog.md, README.md, src/disasm.rs, src/main.rs, src/opts.rs
Mostly changes to disassembler (compile with "disasm" feature, pass `--disasm`)
- don't include constants by default
- include local jump labels in disassembly
- include instructions in hex in disassembly
- avoid memory addresses with displacement in disassembly
- bump bpaf
=> Release 0.2.35

.github/workflows/check-and-lint.yaml, src/asm.rs
We need to strip underscore on 32bit Windows and MacOS and leave it as is on Linux and 64bit  Windows.
Fixes https://github.com/pacak/cargo-show-asm/issues/137
=> Test mangled named on Windows too

Cargo.lock, Cargo.toml
- support `--config KEY=VAL` option that is passed directly to cargo (#305)
- bump deps
=> Release 0.2.39

src/lib.rs
When an item is specified in arguments, it is expected that no matter how many items are found, the requested item will be shown. When the `--everything` option is given, it is expected that no matter how many items are found, "everything" will be shown.
Currently (without this PR) if there is only one item found, it will always return only this item, regardless of what is requested on the command line.
This PR moves the automatic selection of a single item later,  after checking that we have not selected anything (or `--everything`) for display.
Also, if you don't mind, this PR removes the unnecessary `expect` and `unreachable` in the moved fragment with a little refactoring. I can revert some of the changes if something is not okay or less readable.
```rust
pub static DATA: &[u8] = &[1, …
```
=> Fix item selection if there is only one item found

Cargo.lock, Cargo.toml, Changelog.md
- more consistend behavior when only one item is detected (#312)
- fixed llvm output for no_mangle functions (#313)
- bump deps
=> Release 0.2.40

Changelog.md, src/asm.rs, src/demangle.rs
Regexp find returns the whole group, including non capturing part, so we can't use it directly. This MR makes regexes more private and uses capture groups to extract labels
Fixes #318
=> Make sure not to drop used labels

.github/workflows/check-and-lint.yaml, src/asm.rs
=> Range is not inclusive, so we must shift end by one

Cargo.lock, Cargo.toml, Changelog.md, README.md, src/asm.rs, src/asm/statements.rs, src/main.rs, src/opts.rs
In short - a whole lot of bugfixes
- make sure not to drop used labels (#318)
- add `release-lto` profile for slightly smaller/faster version - you have to use it yourself, by default it is still `release`
thanks zamazan4ik for the suggestion
- detect and render merged functions (#310)
- update docs (#320)
- smarter approach for detecting constants (#315)
- smarter CI (#79)
- bump deps
=> Release 0.2.41

.github/workflows/check-and-lint.yaml, Cargo.lock, Cargo.toml, Changelog.md, src/asm.rs
- `--quiet` option that gets passed to `cargo
- Also search for context in `.set` statements - for merged functions
this mean that when you are showing the alias with `-c 1` - the actual
implementation will show up as well (Fixes #338)
=> Release 0.2.42

src/main.rs
I suggest printing  the `cargo` command used to generate the output in verbose output mode.
`cargo asm` is very handy, but sometimes it is more convenient to use a lower-level command. Then `cargo asm -v` can help by telling you what flags you can use to get a similar output. And also just for debugging purposes.
The change is based on similar code from `Mca::dump_range`:
https://github.com/pacak/cargo-show-asm/blob/60cf36623ad04e78d008db1a6a433be5db5491a3/src/mca.rs#L59-L61
but using capitalized "Running" word and colon (more consistent with other printed information from cargo-show-asm), and verbosity `>= 1` condition (similar to `cargo` verbosity for printing running commands).
`cargo run -- --bin cargo-asm -v`
```
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.02s …
```
=> Trace used cargo command in verbose mode

src/main.rs
Fixes https://github.com/pacak/cargo-show-asm/issues/355
This PR fixes passing `target-cpu` to the dependencies using `RUSTFLAGS`  instead of `cargo rustc` `args`.
- user-supplied codegen flags - okay with `cargo rustc` `args`.
- asm syntax - okay with `cargo rustc` `args`.
- `target-cpu` - should be passed as RUSTFLAGS to compile deps with `target-cpu`.
- `debuginfo` - probably don't affect deps, so okay with `cargo rustc` `args`.
- `codegen-units` - probably should be passed as RUSTFLAGS to be applicable for deps, but I am not sure. Please check this. If passed with `RUSTFLAGS` may overwrite user-specified `codegen-units` in `RUSTFLAGS`.
- `RUSTFLAGS` are prioritized over `cargo rustc` `args`, so `cargo asm --native` or `cargo asm --target-cpu=CPU` will now overwrite user-specified …
=> Fix passing target-cpu and codegen-units to dependencies

README.md, src/asm.rs, src/disasm.rs, src/lib.rs, src/main.rs, src/opts.rs
I have a usecase where it would be nice to use cargo-show-asm programmatically, since it does a nicer job of filtering and demangling than most builtin utilities. However, UI messages currently print to stdout, meaning they need to be manually filtered:
$ cargo asm -p libm --lib 2>/dev/null | cat
Try one of those by name or a sequence number
0 "<f32 as libm::math::support::float_traits::Float>::abs" [9]
1 "<f32 as libm::math::support::float_traits::Float>::copysign" [18]
2 "<f32 as libm::math::support::float_traits::Float>::normalize" [21]
3 "<f64 as libm::math::support::float_traits::Float>::abs" [9]
Introduce a `-s`/`--silent` flag that reduces the verbosity level, effectively being the the opposite of `-v`:
$ path/cargo-asm asm -p libm --lib -s 2>/dev/null | cat
0 "<f32 as …
=> Add a `-s`/`--silent` option to silence user-facing messages

Cargo.lock, Cargo.toml, Changelog.md, src/main.rs
- don't try to override `RUSTFLAGS` unless needed - this should keep `.config/cargo` working (Fixes #364)
=> Release 0.2.47

src/asm.rs, src/lib.rs, src/main.rs, src/mca.rs
An alternative approach to https://github.com/pacak/cargo-show-asm/pull/373, should remove the need to figure out what platforms support/require `.intel_syntax`
=> mca analysis: only include .intel_syntax if original file had it

Cargo.lock, Cargo.toml, Changelog.md
- better support for ARM MCA and disassembly (#378) and (#375)
thanks @kornelski
- default verbosity changes - (#377)
- clippy improvements - (#376)
=> Release 0.2.48

Cargo.lock, Cargo.toml, Changelog.md
- Add a short alias `-F` in addition to `--features` (#390)
thanks @joseluis
- try to support cursed combinations of forward and backward slashes
in file names created in case of crosscompilation (#382)
=> Release 0.2.49

Cargo.lock, Cargo.toml, Changelog.md
- Print links to rust sources as `file:line`, some terminals allow you to click them
thanks @kornelski
- You can also render asm of dependencies using `-p` flag (0b3ffc9bba32f9fc3722b62b01dbbb8c47a0b4f0)
- update deps
=> Release 0.2.50

Cargo.lock, Cargo.toml, Changelog.md, src/asm.rs, src/asm/statements.rs
- Use ~ in place of home dir and relative paths for current project when printing rust source code for both privacy and convenience
Original implementation was done by @kornelski in #404
=> Release 0.2.51

src/asm.rs, src/asm/statements.rs, src/cached_lines.rs, src/demangle.rs, src/disasm.rs, src/lib.rs, src/llvm.rs, src/main.rs, src/mca.rs
Rust started warning about `mismatched_lifetime_syntaxes`. I've also applied a few other clippy lints.
=> Explicit struct lifetimes

Cargo.lock, Cargo.toml, Changelog.md
- support for `cargo` `build-dir` (#409)
=> Release 0.2.52
